language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
matrix:
    include:
        - php: 7.0
          env: coverage=on
        - php: 7.1
          env: coverage=on

    allow_failures:
        - php: 7.2
          env: coverage=off

before_script:
  # Install Nette Tester & Code Checker
  - travis_retry composer install --no-interaction --prefer-dist $dependencies
  #- travis_retry composer create-project nette/code-checker temp/code-checker ~2.8 --no-interaction
  # - if [ "$coverage" == "on" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./app"; fi
  - if [ "$coverage" == "on" ]; then coverageArgs="--coverage ./coverage.xml --coverage-src ./app"; fi

script:
  - vendor/bin/tester tests -s -c tests/php-unix.ini $coverageArgs

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

    - >
      if [ "$coverage" == "on" ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      && php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_API_TOKEN" --format=php-clover ./coverage.xml

after_success:
  - coveralls

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
